### ISSUE TITLE
Karma and Todos for Zahi Mizrahi

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-ParkingManagement#12]
_From @zahimizrahi on October 28, 2016 6:37_

- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; 
- [x]  State that you are (not) in search for a job.

_Copied from original issue: SpartanRefactoring/Spartanizer#551_

**Comment by zvili** [comment]
_From @zahimizrahi on October 28, 2016 6:41_

@yossigil : done. 
(I couldn't assign myself to this issue)

**Comment by zvili** [comment]
_From @dormaayan on October 28, 2016 7:0_

@zahimizrahi : Cool Page (:

**Comment by zvili** [comment]
_From @nisanarz on October 28, 2016 8:54_

Looks great! good luck! :)

**Comment by zvili** [comment]
_From @shaysegal on October 28, 2016 11:45_

Good job! 
check mine #558

**Comment by zvili** [comment]
_From @matityahuinba on October 28, 2016 15:7_

Awesome! Good luck!! :pray:

**Comment by zvili** [comment]
_From @yossigil on October 29, 2016 2:17_

Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?). .
 erase much of the junk you copied from the tutorial. Assign yourself if you havent' done so yet.
Good luck.

**Comment by zvili** [comment]
_From @kfir-marx on October 30, 2016 16:56_

great page :+1:

**Comment by zvili** [comment]
_From @zahimizrahi on November 17, 2016 20:59_

#551 is closed.

**Comment by zvili** [comment]
_From @yossigil on November 18, 2016 5:33_

Did you mean #801 is closed?

**Comment by zahimizrahi** [comment]
Current tasks: 

- [ ]  #46 - **working on it now**

**Comment by yossigil** [comment]
@zahimizrahi : I think yoyu can agree that you did not do much till now...
As to future work: #20 and #21: aren't this duplicates?

**Comment by yossigil** [comment]
20 and 21

**Comment by zahimizrahi** [comment]
@yossigil  that's right, as for now, I didn't. 

as for #20 and #21 - they're not the same. one is sign up screen and the other is sign in screen. 
I changed the title of those issues for making it clearer. thank you!

**Comment by yossigil** [comment]
OK.

Am I in your telegram group? Let's continue there.

**Comment by orimarco** [comment]
How would you rank your amount of contribution to the project compared to others in the group?
Please specify the ordinal of the **quintile**.

**Comment by zahimizrahi** [comment]
I can't compare myself to others  because every one of us is working hard in their areas of responsibility.
As I see it, the project should be based on teamwork and not competitiveness between us. I can tell you each member does his/her best for the project even if it's not numbered by commits.

I would rank my contribution to the project as 4/5 - I'm working hard and put a lot of effort on this project but I'm still in learning process with JavaFX so I didn't contribute much to the project yet.
I'm sure my amount of contribution will grow in the next weeks.

**Comment by orimarco** [comment]
@zahimizrahi  feel free to ignore 😄 
keep up the good work!

**Comment by yossigil** [comment]
Q5

**Comment by zahimizrahi** [comment]
**Weekly Report - 2th Week** (11-17/12) 

- I converted the project to maven (as explained in #57).  added pom.xml and helped other difficulties with maven of other team members. 
- I shared the project with `travis`, a tool for continuous integration (as explained in #58 ). I and @DavidCohen55  made a meeting with Zvi on Sunday in order to solve some permission issues. I'm also write a short guide (as explained in #62) for all the team how to sign up to `travis-ci`. 
- I keep dealing with #55 (learning `javaFX`). It's a long issue so I didn't finish it all but a huge process have been made. 5/24 left. 
- I created a wiki about `javaFX `application.
- I finished issue #20 and made log in screen. 
- @Shahar-Y made the main menu screen (as explained in #23).  I integrated my screen and modules with it. There's still some connection we need to do between the screens but it is almost ready. 
- I started working on the opening screen (as explained in #22). 

**Plan for 3th Week of the Sprint** (18-24/12) 

- [x]  finish learning javaFX (and close issue #55). 
- [x] finish opening screen (#23). 
- [x] working on sign in screen (#21).

**Comment by zahimizrahi** [comment]
**Weekly Report - 3th Week** (18-24/12) 
- I finished the learning process of Java and closed issue #55. 
- I finished cool opening screen (#23). Implemented it as flush screen (similar to Eclipse/Photoshop system as you can see). 
- Integrated GetPassByEmail & Login screen (#80).  I closed this issue.
-  fixed runtime error in GUI flow (issue #75). 
- keep working on main menu screen with @Shahar-Y  (issue #20).
- created basic sign in screen. there's still work left to do there (issue #21). 

**Plan for 4th Week of the Sprint** (24-31/12) 
- [x] finish register screen (#21). 
- [x] finish main menu (#20). 
- [x]  customize css template for all Driver GUI.
- [x] open a wiki about css.

and maybe (?)
- [x]  working on logout - **done by @Shahar-Y .** 
- [x]  including the graphic map in GUI.

**Comment by yossigil** [comment]
Wow!

**Comment by zahimizrahi** [comment]
**Weekly Report - 4th Week** (25-31/12) 

- I finished main menu screen and closed issue #20. 
- I finished register screen, and closed issue #21. 
- I created  helpful page about wiki (closed issue #84). 
- I made CSS template for all screens in GUI (issue #85 - also closed). 
- I integrated the graphic map (of issue #68) in GUI as described in issue #86 (also closed).
- I made some few changes in GUI such as hoverable buttons and framing the screens. 

**Plan for 5th Week of the Sprint** (1-7/1) 
- [x] renovating the main GUI screen.
- [x]  add navigation screens for GUI (depends on sefialbo) (?) 
- [x] start working on Manager GUI screens (depends on ortroyaner) (?)
- [x] add framework for testing GUI (only if I'll find something compatible to the project)

**Comment by zahimizrahi** [comment]
**Weekly Report - 5th Week** (1-7/1) 
I wasn't doing much due to personal issues, and besides, there isn't much left to do in the GUI part anyway... 

- renovating the main menu screen, and closed issue #91. 
- presented the project in the meeting with staff in 2/1.
-  planning the next gui screens. 


**Plan for 6th Week of the Sprint** (8-14/1) 
- [x]  add navigation screens for GUI (depends on sefialbo) (?) 
- [x] start working on Manager GUI with @Shahar-Y  (#94, #95, #96).

**Comment by zahimizrahi** [comment]
**Weekly Report - 6th Week** (8-14/1) 
There isn't so much left doing in this sprint 

- trying to add TestFX to the project (did it, but it wasn't compatible to our project :( ) - issue #102. 
- creating 'About' screen (issue #106). 
- updating GUI skeleton 
- renovating the css style of the project 



**Plan for 7th Week of the Sprint **  (15-21/1) 
mostly closing all of the issues (helping others closed their issues, since I don't have issues left).
also, writing the final report & presentation of the project.

**Comment by zahimizrahi** [comment]
**Weekly Report -  7th Week of the Sprint (15-21/1)**

- working on issue #115 (Add icons to buttons). there's still some changed needs to be done (probably in the next sprint). 
- writing the final presentions: Features of GUI, Summary of Driver GUI and Future Directions. 
- fixing some minor bugs in the gui.

**Comment by yossigil** [comment]
Good job Zahi, as usual.
