### ISSUE TITLE
Karma and Todos for David Cohen

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-ParkingManagement#9]
_From @DavidCohen55 on October 30, 2016 18:15_

- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

_Copied from original issue: SpartanRefactoring/Spartanizer#639_

**Comment by zvili** [comment]
_From @DavidCohen55 on October 30, 2016 18:23_

@yossigil: Done. I can't assign myself

**Comment by zvili** [comment]
_From @assaflu on October 30, 2016 18:36_

I liked your issue, i would appriciate if you would chek mine #640

**Comment by zvili** [comment]
_From @rodedzats on October 30, 2016 21:2_

💯 mem 
come to #656

**Comment by zvili** [comment]
_From @sefialbo on October 31, 2016 8:34_

Cool issue, check mine: #666

**Comment by zvili** [comment]
_From @shaysegal on October 31, 2016 14:42_

![bitmoji](https://render.bitstrips.com/v2/cpanel/7897753-204257602_3-s4-v1.png?transparent=1&width=246)

**Comment by zvili** [comment]
_From @AdiOmari on November 1, 2016 8:0_

Add teaching and quality assurance labels. To assign yourself you must be invited to the project, which is done once you do assignment 0.

**Comment by zvili** [comment]
_From @Shahar-Y on November 3, 2016 12:15_

The only way I can describe the feeling I had while first entering David's karma page is by asking you to imagine diving into an endless ocean. And in this ocean, the water is made of pure happiness; the fish are the most colourful and life-like comments of the people supporting the page. The corals are made of David's amazing personality, wich holds together this entire world he created. 
I know in my heart, that this is a sanctuary of peace and quite for when the worries and fears of the world seem to be crushing your soul.
I will never get tired of wisiting this page. For me,  #639 has become a number representing all that is good in this world.


Also, check out mine at #665 :)

**Comment by DavidCohen55** [comment]
I'm posting here the current issues that I will be working on,
I will be in charged of:
- issue #32 
- issue #33 and will work with @matityahuinba.
also I'm involved in issue #41 with @dshames.
This comment will be updated if changes occur.

**Comment by orimarco** [comment]
How would you rank your amount of contribution to the project compared to others in the group?
Please specify the ordinal of the **quintile**.

**Comment by zahimizrahi** [comment]
I can't compare myself to others in project because every one of us is working hard in their areas of responsibility. 
As I see it, the project should be based on teamwork and not competitiveness between us. I can tell you  member does his/her best for the project even if it's not numbered by commits. 

I would rank my contribution to the project as 4/5 - I'm working hard and put a lot of effort on this project but I'm still in learning process with JavaFX so I didn't contribute much to the project yet. 
I'm sure my amount of contribution will grow in the next weeks.

**Comment by DavidCohen55** [comment]
I don't compare myself to the other team members, by my opinion everyone are doing a great jobs at their parts of work and showing a good teamwork with each other.
Until now I worked not only in the git but also I managed the team, making sure everyone knows what he/she is doing in the project and that no one is being left out.
Also one of the things I do is starting to write the logic of the project and until now we were depending on the database and server to be up so the "Logic team" could start working better, but although this limitation we continued working and showing progress, and in the next few days we are going to start working with the data from the server.

**Comment by orimarco** [comment]
feel free to ignore 😄

**Comment by DavidCohen55** [comment]
I've found @zahimizrahi weekly report very efficient so I decided to make one as well:
**Weekly Report - 3th Week** (18-24/12) 
1. I finished the the registration functions and closed the issue (#33), which include:
- Sign up, adds a new row to the DB
- Log in, check in the DB for a user
- Information update, modified a row to the DB
2. I made tests for the DB to see that all of the information I need is being saved.
3. Started working on connecting the function to the relevant GUI #78 
4. Presented with @Shahar-Y,@dshames and @shaysegal the project status in this week meeting to @idabran & @zvili.
5. Started making a draft for the wiki #70 .

**Plan for 4th Week of the Sprint** (25-31/12) 
- [x] Finish the wiki page #70 .
- [x] Continue the connection between the GUI and update information function #78.
- [x] Start the connection between the GUI and register function #79. 
- [x]  modified User class to work with a pointer to Parking Slot. #81 

hope to achieve more in this week 😃.

**Comment by DavidCohen55** [comment]
Due to an illness I've couldn't work in the last week so in this report will be  about the 4th week and the goals for this week.

Weekly Report - 4th Week (18-24/12)
- Finish the wiki page and closed issue #70 .
- Finish the GUI update for using update information function and closed issue #78.
- Finish the GUI update for using register function and closed issue #79.
- Modified User class to work with a pointer to Parking Slot and closed issue #81
- Update few of the tests I've already written and added a new ones to check new functionalities 

Plan for 6th Week of the Sprint (25-31/12)
- [x] Populate the User class in the database. #97
- [x] Checking few more cases in the tests.
- [ ] Starts to write the report for the end of the semester
- [ ] Divide the work for the end of the semester within the group: report, PowerPoint presentation...
